/* Generated by RuntimeBrowser.
   Image: /System/Library/PrivateFrameworks/WebKit.framework/WebKit
 */
#import "WebHistoryItem.h"
@class WebBackForwardListPrivate;

@interface WebBackForwardList : NSObject  {
    WebBackForwardListPrivate *_private;
}

+ (void)initialize;

- (void)_close;
- (id)description;
- (void)dealloc;
- (id)init;
- (void)addItem:(WebHistoryItem*)arg1;
- (void)setToMatchDictionaryRepresentation:(id)arg1;
- (id)dictionaryRepresentation;
- (void)goForward;
- (void)goBack;
- (WebHistoryItem*)currentItem;
- (void)finalize;
- (WebHistoryItem*)backItem;
- (WebHistoryItem*)itemAtIndex:(int)arg1;
- (void)setPageCacheSize:(unsigned int)arg1;
- (int)capacity;
- (void)removeItem:(WebHistoryItem*)arg1;
- (int)forwardListCount;
- (int)backListCount;
- (unsigned int)pageCacheSize;
- (void)setCapacity:(int)arg1;
- (WebHistoryItem*)forwardListWithLimit:(int)arg1;
- (WebHistoryItem*)backListWithLimit:(int)arg1;
- (WebHistoryItem*)forwardItem;
- (void)goToItem:(WebHistoryItem*)arg1;
- (BOOL)containsItem:(WebHistoryItem*)arg1;


@end
